### PR TITLE
Vertex as &'static str

### PR DESCRIPTION
**Pull request by nikarh**
For glium/glium#2056

### CODE REVIEW

**Review by est31 — APPROVED** [review]

**Comment by nikarh** [comment]
Hey, hi!

I'm sorry, I think I should have made it more clear, this PR depended on https://github.com/glium/glium/pull/2056.

Though if https://github.com/glium/glium/pull/2056 gets approved it shouldn't be much of an issue

**Comment by est31** [comment]
Oh I've thought the dependency was going the other way around.

**Comment by est31** [comment]
Sorry, I'll revert. Obviously, the glium_derive crate depends on glium... (correction: it's not a strict cargo dependence but a correspondence rather)

**Comment by nikarh** [comment]
No problem, I'll open it in a new PR if the one in `glium` gets merged

**Pull request merged**
